config/routes.rb
Rails.application.routes.draw do
  resources :stories
  resources :comments, only: [:create]

  root 'stories#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :story
end

app/models/story.rb
class Story < ActiveRecord::Base
	mount_uploader :image, ImageUploader

	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@comment = Comment.new(comment_params)
		@comment.save

		redirect_to @comment.story
	end

	private

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :story_id)
    end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @comment = Comment.new
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :content, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Relay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-custom navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Relay", root_path, class: "navbar-brand" %>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/stories/_form.html.erb
<%= simple_form_for(@story) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<header class="intro-header" style="background-image: url('<%= asset_path('home-bg') %>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="page-heading">
                    <h1>Relay</h1>
					<hr class="small">
					<span class="subheading">우리의 이야기를 잇다</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
	<div class="row">
		<% @stories.each do |story| %>
			<%= link_to story do %>
				<div class="col-xs-6 col-md-4">
				    <div class="thumbnail">
				      <%= image_tag(story.image_url(:thumb)) %>
				      <div class="caption">
				        <h3><%= story.title %></h3>
				      </div>
				    </div>
				</div>
			<% end %>
		<% end %>
		</div>
	<%= link_to 'New Story', new_story_path, class: "btn btn-default" %>
	<hr>
</div>

app/views/stories/new.html.erb
<header class="intro-header" style="background-image: url('<%= asset_path('home-bg') %>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="page-heading">
                    <h1>New Story</h1>
					<hr class="small">
					<span class="subheading">새로운 스토리를 시작해보세요!</span>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">

	<%= render 'form' %>

	<%= link_to 'Back', stories_path %>
</div>

app/views/stories/show.html.erb
<header class="intro-header" style="background-image: url('<%= @story.image_url %>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="page-heading">
                    <h1><%= @story.title %></h1>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
	<p>
		<%= simple_format @story.content %>
	</p>
	<% @story.comments.each do |comment| %>
		<p><%= simple_format comment.content %></p>
	<% end %>

	<%= simple_form_for @comment do |f| %>
		<%= f.input :content, label: "위의 내용에 이어서 이야기를 써주세요!" %>
		<%= f.hidden_field :story_id, value: @story.id %>
		<%= f.submit "등록하기", class: "btn btn-default" %>
	<% end %>

	<%= link_to 'Edit', edit_story_path(@story) %> |
	<%= link_to 'Back', stories_path %>
</div>